config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to:"main#landing_page"

  post 'main/select_room'
  post 'main/select_room_slots'
  post 'main/make_booking'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booked_slot.rb
class BookedSlot < ApplicationRecord
    validates :slot_id, presence: true
    validates :room_id, presence: true
    validates :on_date, presence: true
    validates :name, presence: true
    validates :email, presence: true, format: { with: /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\z/ }
    belongs_to :slot
end

app/models/room.rb
class Room < ApplicationRecord
    attr_accessor :select_a_date

    validates :name, presence: true

    has_many :slots
end

app/models/slot.rb
class Slot < ApplicationRecord
    attr_accessor :slot_id, :name, :email

    validates :time, presence: true

    belongs_to :room
    has_one :booked_slot , dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    include BookingHelper

    def landing_page
        @room = Room.new
    end #landing_page


    def select_room
                
        @selected_date = params[:room][:select_a_date] if params[:room][:select_a_date].present?
                
        @room = Room.new

        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: turbo_stream.update("select_room", partial: "main/select_room",        
            locals: {selected_date: @selected_date, room: @room})
          end
        end

    end #select_room


    def select_room_slots        

        @room = Room.find(params[:room][:name])
        @slots = @room.slots
        @selected_date = params[:room][:selected_date]
        @slot = Slot.new
        
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: turbo_stream.update("select_room_slots", partial: "main/select_room_slots",
            locals: {selected_date: @selected_date, room: @room, slots: @slots, slot: @slot })
          end
        end

    end #select_room_slots


    def make_booking

        slot = params[:slot] if params[:slot]
        slot_id = slot[:slot_id]
        selected_date = slot[:selected_date]
        room_id = slot[:room_id]

        if if_booking_exists(slot_id, selected_date, room_id) 
            @booking_response_text = "Booking exists, please select another slot."
            @booking_response_text_class = "message_error"
        else    
            make_new_booking(slot)
            if @slot_booked.valid?
                @booking_response_text = "Booking saved successfully!"
                @booking_response_text_class = "message_success"
            else
                @booking_response_text = "Error in booking : #{@slot_booked.errors.full_messages.first}"
                @booking_response_text_class = "message_error"
            end
        end

        respond_to do |format|
            format.turbo_stream do
                render turbo_stream: turbo_stream.update("booking_message", partial: "main/booking_response",
                locals: {booking_response_text: @booking_response_text, booking_response_text_class: @booking_response_text_class})
            end
        end     

    end #make_booking

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_helper.rb
module BookingHelper

    def booked_by_user(selected_date, slot, room_id)

        slot_is_booked = Slot.joins(:booked_slot)
                             .where(booked_slots: {on_date: selected_date, slot_id: slot.id, room_id: room_id})
                             .pluck("booked_slots.email")
                             .map{|email| {email: email}}

        slot_is_booked.empty? ? '-' : slot_is_booked[0][:email]

    end #booked_by_user


    def if_already_booked(slot, selected_date, room_id)
        
        if_booked = if_booking_exists(slot.id, selected_date, room_id)

        if_booked.present? ? true : false 

    end #if_already_booked


    def if_booking_exists(slot_id, selected_date, room_id)        
        
        booking_exists =  Slot.joins(:booked_slot)
                     .where(booked_slots: {slot_id: slot_id, on_date: selected_date, room_id: room_id})
                     .pluck("booked_slots.id")

        booking_exists.present? ? true : false

      end #if_booking_exists


    def make_new_booking(booking_params)
        @slot_booked = BookedSlot.create(slot_id: booking_params[:slot_id],
                                          room_id: booking_params[:room_id],
                                          name: booking_params[:name],
                                          email: booking_params[:email],                                          
                                          on_date: booking_params[:selected_date])

        @slot_booked.valid? ? true : false
          
      end #make_new_booking

end

app/helpers/room_helper.rb
module RoomHelper
    
    def get_room_list
        Room.all.count > 0 ? Room.all.map{ |room| [room.name, room.id]} : []
    end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GtBookingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="mt-4">
          <div class="col text-center">            
              <%= yield %>            
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/main/_booking_response.html.erb
<div class="mt-4">

<div class="<%= booking_response_text_class %>">
    <%= booking_response_text %>
</div>

app/views/main/_select_date.html.erb
<div>
    <%= form_for(@room, url: main_select_room_path) do |r| %>

        <%= r.date_field :select_a_date, min: Date.today + 1, value: (Date.current + 1.day).to_s, required: true %>

        <%= r.submit 'Choose Date', class: 'btn btn-primary' %>

    <% end %>
</div>

app/views/main/_select_room.html.erb
<% if selected_date %>

    <div class="mt-4"></div>

    <h3>Select a room</h3>

    <div class="mt-1"></div>
    <%= form_for(room, url: main_select_room_slots_path) do |r| %>        
        
        <%= r.select :name, get_room_list, class: 'form-select' %>
        <%= r.hidden_field :selected_date, :value => selected_date %>
        <%= r.submit 'Check room slots', class: 'btn btn-primary' %>
        </span>
    <% end %>

<% end %>

app/views/main/_select_room_slots.html.erb
<% if selected_date.present? && (room.present? && slots.present?) %>
    <div class="mt-4">
        <p>Only allowed to book 1 hour slots. Meetings longer than 1 hour might be an inefficient use of time.</p>
    </div>
    <div class="mt-4">
        <%= form_for(slot, url: main_make_booking_path) do |form| %>
            <table class="table table-striped">
                <tr>
                    <th>Start Time</th>
                    <th>Booked by</th>
                    <th>Select</th>
                </tr>
                <% slots.each_with_index do |sl, index| %>
                    <tr>
                        <td><%= sl.time %></td>
                        <td><%= booked_by_user(selected_date, sl, room.id) %></td>
                        <td><%= form.radio_button :slot_id, sl.id , id: "radio_hit_#{index = index + 1}" , :disabled => if_already_booked(sl, selected_date, room.id) %></td>
                    </tr>
                <% end %>
            </table>

            <div class="mt-4">
                <%= form.label :name %>
                <%= form.text_field :name, required: true %>
            </div>

            <div class="mt-4">
                <%= form.label :email %>
                <%= form.text_field :email, required: true %>
            </div>

            <%= form.hidden_field :selected_date, value: selected_date %>
            <%= form.hidden_field :room_id, value: room.id %>

            <div class="mt-4">
                <%= form.submit "Book Now", class: 'btn btn-primary'%>
            </div>

        <% end %>
    </div>
<% end %>

app/views/main/landing_page.html.erb
<h1>BOOK YOUR ROOM!</h1>

    <div class="row mt-4">
    <h3>Select a date</h3>

    <%= render partial: "main/select_date",  locals: {room: @room}%>

    <div id="select_room">
        <%= render partial: "main/select_room", locals: {selected_date: @selected_date, room: @room } %>
    </div>

    <div id="select_room_slots">
        <%= render partial: "main/select_room_slots", locals: {selected_date: @selected_date, room: @room, slots: @slots, slot: @slot } %>
    </div>

    <div id ="booking_message">
        <%= render partial: "main/booking_response", locals: {booking_response_text: @booking_response_text, booking_response_text_class: @booking_response_text_class } %>
    </div>

</div>